# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('postal_code', models.CharField(max_length=6)),
                ('street', models.TextField()),
                ('home_nr', models.CharField(max_length=5)),
                ('apartment_no', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Car_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.PositiveSmallIntegerField(choices=[(1, 'Register'), (2, 'Unregister'), (3, 'Temporary Register')])),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('application_date', models.DateField()),
                ('application_place', models.TextField()),
                ('attachment_no_1', models.TextField(blank=True)),
                ('attachment_no_2', models.TextField(blank=True)),
                ('attachment_no_3', models.TextField(blank=True)),
                ('attachment_no_4', models.TextField(blank=True)),
                ('attachment_no_5', models.TextField(blank=True)),
                ('attachment_no_6', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car_brand',
            fields=[
                ('brand_name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Car_const',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=17)),
                ('year', models.PositiveSmallIntegerField()),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car_var',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('registration_no', models.CharField(max_length=10)),
                ('const_vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_const')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.TextField()),
                ('REGON', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PESEL', models.CharField(max_length=11)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_car',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='car_var',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Person'),
        ),
        migrations.AddField(
            model_name='car_model',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_type'),
        ),
        migrations.AddField(
            model_name='car_const',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_model'),
        ),
        migrations.AddField(
            model_name='car_const',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_type'),
        ),
        migrations.AddField(
            model_name='car_application',
            name='applicant_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Company'),
        ),
        migrations.AddField(
            model_name='car_application',
            name='applicant_private',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Person'),
        ),
        migrations.AddField(
            model_name='car_application',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car_var'),
        ),
        migrations.AddField(
            model_name='car_application',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Office'),
        ),
        migrations.AddField(
            model_name='car_application',
            name='owner_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Address'),
        ),
    ]
