# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-27 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20160827_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_application',
            name='applicant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Company'),
        ),
        migrations.AlterField(
            model_name='car_application',
            name='applicant_private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Person'),
        ),
    ]
