# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('postal_code', models.CharField(max_length=6)),
                ('street', models.TextField()),
                ('home_nr', models.CharField(max_length=5)),
                ('apartment_no', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CarApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.PositiveSmallIntegerField(choices=[(1, 'Register'), (2, 'Unregister'), (3, 'Temporary Register')])),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('application_date', models.DateField()),
                ('application_place', models.TextField()),
                ('attachment_no_1', models.TextField(blank=True)),
                ('attachment_no_2', models.TextField(blank=True)),
                ('attachment_no_3', models.TextField(blank=True)),
                ('attachment_no_4', models.TextField(blank=True)),
                ('attachment_no_5', models.TextField(blank=True)),
                ('attachment_no_6', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('brand_name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(max_length=17)),
                ('year', models.PositiveSmallIntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, null=True)),
                ('registration_no', models.CharField(max_length=10)),
                ('const_vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarConst')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.TextField()),
                ('REGON', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PESEL', models.CharField(max_length=11)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carvar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Person'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='carconst',
            name='CarModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='carconst',
            name='CarType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarType'),
        ),
        migrations.AddField(
            model_name='carconst',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarBrand'),
        ),
        migrations.AddField(
            model_name='carapplication',
            name='applicant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Company'),
        ),
        migrations.AddField(
            model_name='carapplication',
            name='applicant_private',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Person'),
        ),
        migrations.AddField(
            model_name='carapplication',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarVar'),
        ),
        migrations.AddField(
            model_name='carapplication',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Office'),
        ),
        migrations.AddField(
            model_name='carapplication',
            name='owner_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Address'),
        ),
    ]
